### ISSUE TITLE
Default recipe fails (ubuntu-12.04 w/ vagrant)

### ISSUE THREAD

**Issue by objectline** [bryanwb/chef-tomcat#6]
##### Included are the relevant lines from the vagrant output. This happens on a fresh ubuntu-12.04 install.

2012-09-24T03:22:00+00:00] INFO: Processing package[tomcat7] action install (tomcat::package line 46)
[2012-09-24T03:22:00+00:00] DEBUG: package[tomcat7] checking package status for tomcat7
[2012-09-24T03:22:00+00:00] DEBUG: package[tomcat7] current version is nil
[2012-09-24T03:22:00+00:00] DEBUG: package[tomcat7] candidate version is 7.0.26-1ubuntu1.1
[2012-09-24T03:22:00+00:00] DEBUG: Executing apt-get -q -y install tomcat7=7.0.26-1ubuntu1.1
[2012-09-24T03:22:14+00:00] DEBUG: ---- Begin output of apt-get -q -y install tomcat7=7.0.26-1ubuntu1.1 ----
[2012-09-24T03:22:14+00:00] DEBUG: STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  authbind libcommons-collections3-java libcommons-dbcp-java
  libcommons-pool-java libecj-java libservlet3.0-java libtomcat7-java

/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/mixin/template.rb:43:in `rescue in render_template'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/mixin/template.rb:39:in`render_template'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider/template.rb:104:in `render_with_context'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider/template.rb:50:in`action_create'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/provider.rb:119:in `run_action'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource.rb:593:in`run_action'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/runner.rb:49:in `run_action'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/runner.rb:81:in`block (2 levels) in converge'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/runner.rb:81:in `each'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/runner.rb:81:in`block in converge'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection.rb:94:in `block in execute_each_resource'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection/stepable_iterator.rb:116:in`call'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection/stepable_iterator.rb:85:in`step'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection/stepable_iterator.rb:55:in`each_with_index'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/resource_collection.rb:92:in `execute_each_resource'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/runner.rb:80:in`converge'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/client.rb:378:in `converge'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/client.rb:420:in`do_run'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/client.rb:176:in `run'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/application/client.rb:283:in`block in run_application'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/application/client.rb:270:in `loop'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/application/client.rb:270:in`run_application'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/lib/chef/application.rb:70:in `run'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-10.14.2/bin/chef-client:26:in`<top (required)>'
/opt/ruby/bin/chef-client:19:in `load'
/opt/ruby/bin/chef-client:19:in`<main>'
[2012-09-24T03:22:15+00:00] FATAL: Chef::Mixin::Template::TemplateError: undefined method `shutdown_wait' for #Hash:0x86fb654
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chef-client -c /tmp/vagrant-chef-1/client.rb -j /tmp/vagrant-chef-1/dna.json

**Comment by justabu** [comment]
Any updates on this one ? We are currently facing the same issue, Looks like we are trying to access attr_accessors from a hash.
